### PR TITLE
stdlib test fix

### PR DESCRIPTION
**Pull request by ryanking13**
Fixes sqlite3 and distutils tests.

Also disable autograd, which I think it doesn't support python3.11.

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks @ryanking13! I didn't notice this for a while...

**Comment by hoodmane** [comment]
> `autograd` which I think it doesn't support python3.11.

Well the actual autograd error is very hard for me to understand
```py
try:
    from inspect import getfullargspec as _getargspec  # Python 3
except ImportError:
    from inspect import getargspec as _getargspec  # Python 2
```
The error occurs on the second import in the except clause. But the first import should succeed? I don't understand why it ever got to that line. If I run that same code manually it works fine...

**Comment by hoodmane** [comment]
Anyways, if you are willing to investigate further why the autograd exception is happening too I would appreciate it.

**Comment by ryanking13** [comment]
> The error occurs on the second import in the except clause. But the first import should succeed? I don't understand why it ever got to that line. If I run that same code manually it works fine...

It seems like it will be fixed by updating to 1.5. (https://github.com/HIPS/autograd/commit/116f738c3e3e180d0219e046f2ba795cd0baae47), which you already did in your PR :)
The autograd team doesn't make tags for each release so it was hard to notice...

**Pull request merged**
